# TODO: implement this workflow

permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    # run once a day at 00:00
    - cron: "0 0 * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno task start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
