# TODO: implement this workflow

on:
  push:
    branches:
      - main
  schedule:
    # run once a day at 00:00
    # - cron: "0 0 * * *"/
    # run once a minute
    - cron: "*/1 * * * *"

jobs:
  run_script:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno task start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NAME: ${{ secrets.CGQAQ_NAME }}
          EMAIL: ${{ secrets.CGQAQ_EMAIL }}
